version: '3.7'
# ELK: Elasticsearch - Logstash - Kibana
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  #kibana
  kibana:
    image: kibana:7.9.2
    ports:
      - 5601:5601
  # Logstash
  logstash:
    image: logstash:7.9.2
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: .
        target: /usr/share/logstash/pipeline
        read_only: true
